name: Initialize project

on:
  push:
    branches:
      - init
    # file paths to consider in the event. Optional; defaults to all.
    # paths:
    #  - 'test/*'
    
jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14]
    
    steps:
    - uses: actions/checkout@v1
    
    # https://github.com/actions/checkout/issues/6
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
      
    #- name: Update the remote origin
    #  run: git remote set-url origin https://$WK_TOKEN:x-oauth-basic@github.com/thecb4/WorkingCopyTest
    
    - name: Create new swift package    
      run: swift package init --type executable
      
    - name: Add new files to repository
      run: git add .
      
    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v2
      env:
        GITHUB_TOKEN: ${{ secrets.WK_TOKEN }}
        PUSH_BRANCH: 'init'