name: Initialize project

on:
  push:
    branches:
      - init
    # file paths to consider in the event. Optional; defaults to all.
    # paths:
    #  - 'test/*'
    
jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14]
    
    steps:
    - uses: actions/checkout@v1
    
    # https://github.com/actions/checkout/issues/6
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
    
    - name: Create new swift package    
      run: swift package init --type executable
      
    - name: Add new files to repository
      run: git add . && git commit -m "initializing swift pacakge"
      
    - name: Checking the git status
      run: git status
      
    - name: push work back to github
      run: git push origin init:init