name: CI/CD

on: [push]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-14.04, ubuntu-18.04, macOS-10.14]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: xcode-build
      if: matrix.os == "macOS-10.14"
      run: xcodebuild


  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-14.04, ubuntu-18.04, macOS-10.14]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.


  package:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-14.04, ubuntu-18.04, macOS-10.14]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
  deploy:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-14.04, ubuntu-18.04, macOS-10.14]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.